### ISSUE TITLE
NameError: name 'os' is not defined

### ISSUE THREAD

**Issue by andrewpgit** [ansible-community/molecule-ec2#3]
When initialization the driver ec2, molocule receives the error. 
The cause of the problem is that the python os module is not imported in the driver.py

from base64 import b64decode
import sys

molecule init scenario --role-name test --driver-name ec2  
--> Initializing new scenario default...
Traceback (most recent call last):
  File "/home/modichord/venv/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/home/modichord/venv/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/modichord/venv/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
 File "/home/modichord/venv/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/modichord/venv/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/modichord/venv/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/modichord/venv/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/modichord/venv/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/modichord/venv/lib/python3.5/site-packages/molecule/command/init/scenario.py", line 237, in scenario
    s.execute()
  File "/home/modichord/venv/lib/python3.5/site-packages/molecule/command/init/scenario.py", line 90, in execute
    self._command_args['driver_name']
  File "/home/modichord/venv/lib/python3.5/site-packages/molecule_ec2/driver.py", line 259, in template_dir
    return os.path.join(
NameError: name 'os' is not defined

**Comment by andrewpgit** [comment]
Could you please, add import os

from base64 import b64decode
import sys
import os

**Comment by RalfLackinger** [comment]
Having the same issues, I modified the file manually and added `import os` and then I could init the scenario without errors.
