### ISSUE TITLE
Unable to Create New Scenario With EC2 Driver

### ISSUE THREAD

**Issue by jenslauterbach** [ansible-community/molecule-ec2#8]
**Summary**

When I try to initialise a new scenario I get the following error:

```
--> Initializing new scenario aws...
Traceback (most recent call last):
  File "/Users/jens/.virtualenvs/molecule-ec2-bug/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/Users/jens/.virtualenvs/molecule-ec2-bug/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jens/.virtualenvs/molecule-ec2-bug/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jens/.virtualenvs/molecule-ec2-bug/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jens/.virtualenvs/molecule-ec2-bug/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jens/.virtualenvs/molecule-ec2-bug/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jens/.virtualenvs/molecule-ec2-bug/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jens/.virtualenvs/molecule-ec2-bug/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jens/.virtualenvs/molecule-ec2-bug/lib/python3.7/site-packages/molecule/command/init/scenario.py", line 237, in scenario
    s.execute()
  File "/Users/jens/.virtualenvs/molecule-ec2-bug/lib/python3.7/site-packages/molecule/command/init/scenario.py", line 90, in execute
    self._command_args["driver_name"]
  File "/Users/jens/.virtualenvs/molecule-ec2-bug/lib/python3.7/site-packages/molecule_ec2/driver.py", line 259, in template_dir
    return os.path.join(
NameError: name 'os' is not defined
```

**Environment**

OS: macOS 10.15.3
Python Version: 3.7.7 (brew install)
Dedicated Virtualenv: ✅ 

**Installed Packages**

* ansible 2.9.6
* molecule 3.0.2
* molecule-ec2 0.1

**Steps to Reproduce**

1. `cd /tmp`
2. `mkvirtualenv molecule-ec2-bug`
3. `pip install molecule`
4. `pip install molecule-ec2`
5. `molecule init role molecule-ec2-bug`
6. `cd molecule-ec2-bug`
7. `molecule init scenario --driver-name ec2 aws`

**Expected Behaviour**

* When I run `molecule init scenario --driver-name ec2 aws` the new scenario using the `ec2` driver is created.

**Actual Behaviour** 

* When I run `molecule init scenario --driver-name ec2 aws` I get the error as described above. The scenario is not created.

**Comment by jenslauterbach** [comment]
I know this is basically a duplicate for #3. I would like to provide a simple PR for this issue to fix it.

**Comment by jenslauterbach** [comment]
I just saw the PR #4. Closing the issue. Please excuse the disruption.
